In [6]:
import torch
my_list = [[1,2,3],[4,5,6]]
tensor = torch.tensor(my_list)
print(tensor)
print(tensor.shape)
print(tensor.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


In [ ]:
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8],[8,9],[9,0]])
print(a @ bmodel = )

tensor([[ 50,  26],
        [122,  77]])


Creating a simple linear layer neural network with torch package

In [8]:
import torch.nn as nn
input_tensor = torch.tensor([[0.3471,0.4547, -0.2356]])
linear_layer = nn.Linear(3,2)
output = linear_layer(input_tensor)
print(output)
print(linear_layer.weight)
print(linear_layer.bias)

tensor([[-0.0044,  0.3146]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[ 0.2293, -0.1848, -0.0145],
        [-0.0329, -0.4765, -0.2221]], requires_grad=True)
Parameter containing:
tensor([-0.0034,  0.4903], requires_grad=True)


a simple linear layer without torch package

In [9]:
input_tensor = torch.tensor(3. , requires_grad = True)
output = input_tensor**2
output.backward()
print(input_tensor.grad)

tensor(6.)


We can stack linear layer with nn.Sequential()

In [14]:
model = nn.Sequential(nn.Linear(8,4),
                      nn.Linear(4,2),
                      nn.Sigmoid())
total = 0
for param in model.parameters():
    total += param.numel()
print(total)

46
